version: '3'
services:
  bot:
    image: "thenumeralone/vettingbot:latest-snapshot"
    env_file:
      - bot.env
    depends_on:
      - db
    restart: always
    deploy:
      resources:
        limits:
          memory: 512m
  db:
    image: "neo4j"
    env_file:
      - db.env
    restart: always
    volumes:
      - data-volume:/data
      - log-volume:/logs
    deploy:
      resources:
        limits:
          memory: 512m
volumes:
  data-volume:
  log-volume: